try {
  console.log("Start of try block");

  lalalala;

  console.log("End of try block (never reached) ðŸ˜¥");
} catch (err) {
  console.log("Error has occurred!");
  console.log(err);
}

console.log("After try block");
